services:
  ducky:
    restart: unless-stopped
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6767:3000
    volumes:
      - ./config:/usr/src/app/config
